INSERT INTO PlayIn (athleteID, venueName) VALUES ('1535420', 'Invalides');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1535429', 'Invalides');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1536648', 'Porte de La Chapelle Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1536650', 'Porte de La Chapelle Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1573440', 'Bercy Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1573441', 'Bercy Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1573442', 'Bercy Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1540704', 'North Paris Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1953447', 'Pont Alexandre III');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1940217', 'Vaires-sur-Marne Nautical Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1940222', 'Vaires-sur-Marne Nautical Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1907200', 'Aquatics Centre');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1544208', 'Aquatics Centre');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1916406', 'Aquatics Centre');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1892360', 'Château de Versailles');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1968081', 'Château de Versailles');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1914909', 'Château de Versailles');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1896517', 'Grand Palais');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1950584', 'Grand Palais');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1889328', 'Grand Palais');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1944856', 'Bordeaux Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1944862', 'Bordeaux Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1944863', 'Geoffroy-Guichard Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1555070', 'Porte de La Chapelle Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1903203', 'Yves-du-Manoir Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1903205', 'Yves-du-Manoir Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1903207', 'Yves-du-Manoir Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1543017', 'Yves-du-Manoir Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1543019', 'Yves-du-Manoir Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1543020', 'Yves-du-Manoir Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1928070', 'Champ de Mars Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1928071', 'Champ de Mars Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1928072', 'Champ de Mars Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1892490', 'Vaires-sur-Marne Nautical Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1892495', 'Vaires-sur-Marne Nautical Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1892500', 'Vaires-sur-Marne Nautical Stadium');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1560283', 'Stade de France');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1560288', 'Stade de France');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1560290', 'Stade de France');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1560315', 'Stade de France');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1902461', 'Marseille Marina');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1931374', 'Marseille Marina');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1950381', 'Marseille Marina');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1950384', 'Marseille Marina');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1915325', 'Chateauroux Shooting Centre');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1915320', 'Chateauroux Shooting Centre');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1953426', 'Chateauroux Shooting Centre');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1565853', 'Paris La Defense Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1918140', 'Paris La Defense Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1910371', 'Grand Palais');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1910362', 'Grand Palais');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1910367', 'Grand Palais');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1958374', 'South Paris Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1958375', 'South Paris Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1567022', 'South Paris Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1894411', 'South Paris Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1551123', 'Champ de Mars Arena');
INSERT INTO PlayIn (athleteID, venueName) VALUES ('1947747', 'Champ de Mars Arena');
