INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1535420', 'Alejandra Valencia', 'F', 'Athlete', '1994-10-17', 'MEX', 'ARC');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1535429', 'Angela Ruiz', 'F', 'Athlete', '2006-07-28', 'MEX', 'ARC');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1536648', 'Kean Yew Loh', 'M', 'Athlete', '1997-06-26', 'SGP', 'BAD');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1536650', 'Wei Han Jessica Tan', 'F', 'Athlete', '1993-07-16', 'SGP', 'BAD');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1573440', 'Marieme Badiane', 'F', 'Athlete', '1994-11-24', 'FRA', 'BKB');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1573441', 'Romane Bernies', 'F', 'Athlete', '1993-06-27', 'FRA', 'BKB');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1573442', 'Alexia Chery', 'F', 'Athlete', '1998-09-05', 'FRA', 'BKB');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1540704', 'Yilmar Leandro Gonzalez Landazury', 'M', 'Athlete', '1993-03-10', 'COL', 'BOX');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1953447', 'Ana Vitoria Magalhaes', 'F', 'Athlete', '2000-10-24', 'BRA', 'CRD');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1940217', 'Jackson Collins', 'M', 'Athlete', '1998-11-05', 'AUS', 'CSP');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1940222', 'Riley Fitzsimmons', 'M', 'Athlete', '1996-07-27', 'AUS', 'CSP');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1907200', 'Timo Barthel', 'M', 'Athlete', '1996-04-03', 'GER', 'DIV');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1544208', 'Alejandro Solarte', 'M', 'Athlete', '2001-09-21', 'COL', 'DIV');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1916406', 'Daniel Restrepo Garcia', 'M', 'Athlete', '2000-03-24', 'COL', 'DIV');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1892360', 'Peter T Flarup', 'M', 'Athlete', '1976-04-10', 'DEN', 'EQU');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1968081', 'Carlos Parro', 'M', 'Reserved Athlete', '1979-06-05', 'BRA', 'EQU');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1914909', 'Isabell Werth', 'F', 'Athlete', '1969-07-21', 'GER', 'EQU');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1896517', 'Karin Miyawaki', 'F', 'Athlete', '1997-02-04', 'JPN', 'FEN');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1950584', 'Jacqueline Dubrovich', 'F', 'Athlete', '1994-07-18', 'USA', 'FEN');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1889328', 'Anne Sauer', 'F', 'Athlete', '1991-04-01', 'GER', 'FEN');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1944856', 'Luis Toomey', 'M', 'Reserved Athlete', '2001-07-01', 'NZL', 'FTL');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1944862', 'Ben Waine', 'M', 'Athlete', '2001-06-11', 'NZL', 'FTL');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1944863', 'Lachlan Bayliss', 'M', 'Athlete', '2002-07-24', 'NZL', 'FTL');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1555070', 'Vera Tugolukova', 'F', 'Athlete', '2008-09-16', 'CYP', 'GRY');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1903203', 'Camille Belis', 'F', 'Athlete', '2004-10-23', 'BEL', 'HOC-F');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1903205', 'Vanessa Blockmans', 'F', 'Athlete', '2002-04-04', 'BEL', 'HOC-F');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1903207', 'Helene Brasseur', 'F', 'Athlete', '2002-01-04', 'BEL', 'HOC-F');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1543017', 'Harmanpreet Singh', 'M', 'Athlete', '1996-01-06', 'IND', 'HOC-M');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1543019', 'Jarmanpreet Singh', 'M', 'Athlete', '1996-07-18', 'IND', 'HOC-M');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1543020', 'Hardik Singh', 'M', 'Athlete', '1998-09-23', 'IND', 'HOC-M');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1928070', 'Hayun Kim', 'F', 'Athlete', '2000-01-07', 'KOR', 'JUD');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1928071', 'Jisu Kim', 'F', 'Athlete', '2000-12-12', 'KOR', 'JUD');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1928072', 'Minjong Kim', 'M', 'Athlete', '2000-09-01', 'KOR', 'JUD');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1892490', 'Sara Maria Johansen', 'F', 'Athlete', '2000-09-13', 'DEN', 'ROW');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1892495', 'Fie Udby Erichsen', 'F', 'Athlete', '1985-04-23', 'DEN', 'ROW');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1892500', 'Caroline Munch', 'F', 'Athlete', '2002-11-13', 'DEN', 'ROW');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1560283', 'Reapi Ulunisau', 'F', 'Athlete', '1994-11-02', 'FIJ', 'RU7');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1560288', 'Laisana Likuceva', 'F', 'Athlete', '1999-02-03', 'FIJ', 'RU7');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1560290', 'Ana Maria Naimasi', 'F', 'Athlete', '1994-02-21', 'FIJ', 'RU7');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1560315', 'Maria Rokotuisiga', 'F', 'Athlete', '2001-06-08', 'FIJ', 'RU7');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1902461', 'Joseph Jonathan Weston', 'M', 'Athlete', '2004-09-10', 'THA', 'SAL');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1931374', 'Arthit Mikhail Romanyk', 'M', 'Athlete', '2001-01-16', 'THA', 'SAL');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1950381', 'Hans Henken', 'M', 'Athlete', '1992-06-04', 'USA', 'SAL');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1950384', 'Noah Lyons', 'M', 'Athlete', '2001-04-30', 'USA', 'SAL');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1915325', 'Diana Bacosi', 'F', 'Athlete', '1983-07-13', 'ITA', 'SHO-F');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1915320', 'Giovanni Pellielo', 'M', 'Athlete', '1970-01-11', 'ITA', 'SHO-M');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1953426', 'Fathur Gustafian', 'M', 'Athlete', '1998-08-21', 'INA', 'SHO-M');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1565853', 'Amro Al-Wir', 'M', 'Athlete', '2001-01-23', 'JOR', 'SWM');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1918140', 'Josh Kirlew', 'M', 'Athlete', '1999-09-09', 'JAM', 'SWM');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1910371', 'Zeqi Zhou', 'F', 'Athlete', '1999-09-25', 'CHN', 'TKW-F');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1910362', 'Zhaoxiang Song', 'M', 'Athlete', '1997-01-29', 'CHN', 'TKW-M');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1910367', 'Yushuai Liang', 'M', 'Athlete', '2000-09-10', 'CHN', 'TKW-M');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1958374', 'Giulia Takahashi', 'F', 'Athlete', '2005-04-02', 'BRA', 'TTN');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1958375', 'Guilherme Teodoro', 'M', 'Athlete', '2001-12-03', 'BRA', 'TTN');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1567022', 'Marie Fegue', 'F', 'Athlete', '1991-05-28', 'FRA', 'WLF');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1894411', 'Suhyeon Kim', 'F', 'Athlete', '1995-02-06', 'KOR', 'WLF');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1551123', 'Austin Klee Gomez', 'M', 'Athlete', '1998-03-19', 'MEX', 'WRE');
INSERT INTO Athlete (athleteID, name, gender, role , birthDate, countryCode, sportsID) VALUES ('1947747', 'Jayden Alexander Lawrence', 'M', 'Athlete', '1994-10-06', 'AUS', 'WRE');
