INSERT INTO Country (countryCode, name) VALUES ('AUS', 'Australia');
INSERT INTO Country (countryCode, name) VALUES ('BEL', 'Belgium');
INSERT INTO Country (countryCode, name) VALUES ('BRA', 'Brazil');
INSERT INTO Country (countryCode, name) VALUES ('CAN', 'Canada');
INSERT INTO Country (countryCode, name) VALUES ('CHN', 'China');
INSERT INTO Country (countryCode, name) VALUES ('COL', 'Colombia');
INSERT INTO Country (countryCode, name) VALUES ('CYP', 'Cyprus');
INSERT INTO Country (countryCode, name) VALUES ('DEN', 'Denmark');
INSERT INTO Country (countryCode, name) VALUES ('FIJ', 'Fiji');
INSERT INTO Country (countryCode, name) VALUES ('FRA', 'France');
INSERT INTO Country (countryCode, name) VALUES ('GER', 'Germany');
INSERT INTO Country (countryCode, name) VALUES ('GRE', 'Greece');
INSERT INTO Country (countryCode, name) VALUES ('INA', 'Indonesia');
INSERT INTO Country (countryCode, name) VALUES ('IND', 'India');
INSERT INTO Country (countryCode, name) VALUES ('ITA', 'Italy');
INSERT INTO Country (countryCode, name) VALUES ('JAM', 'Jamaica');
INSERT INTO Country (countryCode, name) VALUES ('JOR', 'Jordan');
INSERT INTO Country (countryCode, name) VALUES ('JPN', 'Japan');
INSERT INTO Country (countryCode, name) VALUES ('KOR', 'Korea');
INSERT INTO Country (countryCode, name) VALUES ('KSA', 'Saudi Arabia');
INSERT INTO Country (countryCode, name) VALUES ('MAS', 'Malaysia');
INSERT INTO Country (countryCode, name) VALUES ('MEX', 'Mexico');
INSERT INTO Country (countryCode, name) VALUES ('NZL', 'New Zealand');
INSERT INTO Country (countryCode, name) VALUES ('SGP', 'Singapore');
INSERT INTO Country (countryCode, name) VALUES ('THA', 'Thailand');
INSERT INTO Country (countryCode, name) VALUES ('USA', 'United States of America');
