INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1971523', 'Joe Leszner', 'M', 'Coach', 'CAN', 'ARC');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1898950', 'Lisa Thomaidis', 'F', 'Coach', 'GER', 'BKB');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1901810', 'Myungsoo Park', 'M', 'Assistant Coach', 'CHN', 'BKB');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1888241', 'Toshihiro Nishiiri', 'M', 'Goalkeeper Coach', 'JPN', 'FTL');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1944971', 'Michael Mayne', 'M', 'Head Coach', 'NZL', 'FTL');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1945000', 'Keri Sarver', 'F', 'Assistant Coach', 'NZL', 'FTL');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1903900', 'Xavier Reckinger', 'M', 'Assistant Coach', 'BEL', 'HOC-M');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1945457', 'Jeremy Davy', 'M', 'Coach', 'AUS', 'HOC-M');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1927174', 'Alyson Regina Annan', 'F', 'Head Coach', 'CHN', 'HOC-F');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1959400', 'Natalia Klimouk', 'F', 'Coach', 'USA', 'GRY');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1946582', 'Emanuela Maccarani', 'F', 'Coach', 'ITA', 'GRY');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1960844', 'Jocelyn Barrieau', 'F', 'Assistant Coach', 'CAN', 'RU7');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1961586', 'Timoci Volavola', 'M', 'Assistant Coach', 'FIJ', 'RU7');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1950509', 'Emilie Bydwell', 'F', 'Head Coach', 'USA', 'RU7');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1955021', 'William Broderick', 'M', 'Head Coach', 'BRA', 'RU7');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1914566', 'Tobias Hyttel', 'M', 'Coach', 'DEN', 'TKW-M');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1565591', 'Faris Al-Assaf', 'M', 'Coach', 'JOR', 'TKW-M');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1902795', 'Chanatip Sonkham', 'F', 'Coach', 'THA', 'TKW-F');
INSERT INTO Coach (coachID, name, gender, role, countryCode, sportsID) VALUES ('1910382', 'Fantao Kong', 'F', 'Coach', 'CHN', 'TKW-F');
