INSERT INTO Venue (venueName, location, capacity) VALUES ('Aquatics Centre', 'Saint-Denis', 5000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Bercy Arena', 'Paris', 15000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Bordeaux Stadium', 'Bordeaux', 42115);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Champ de Mars Arena', 'Paris', 9000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Château de Versailles', 'Versailles', 80000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Chateauroux Shooting Centre', 'Chateauroux', 3000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Geoffroy-Guichard Stadium', 'Saint-Étienne', 41965);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Golf National', 'Paris', 35000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Grand Palais', 'Paris', 8000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Hôtel de Ville', 'Paris', 1500);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Invalides', 'Paris', 8000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Marseille Marina', 'Marseille', 5000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('North Paris Arena', 'Paris', 6000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Paris La Defense Arena', 'Paris', 15220);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Pont Alexandre III', 'Paris', 1500);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Porte de La Chapelle Arena', 'Paris', 8000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('South Paris Arena', 'Paris', 18000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Stade de France', 'Saint-Denis', 77083);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Stade Roland-Garros', 'Paris', 36000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Vaires-sur-Marne Nautical Stadium', 'Vaires-sur-Marne', 22000);
INSERT INTO Venue (venueName, location, capacity) VALUES ('Yves-du-Manoir Stadium', 'Colombes', 15000);
